config/routes.rb
Rails.application.routes.draw do
  
  resources :imagegalleries
  root 'imagegalleries#showallimages'
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :imagegalleries do
    member do
    delete :delete_upload
    end
  end


 # get 'tags/:tag', to: 'imagegalleries#tagged',as: :tag
  get "/showallimages" => "imagegalleries#showallimages"
  get '/tagged', to: "imagegalleries#tagged", as: :tagged 
  get '/showgallery' , to: "imagegalleries#showgallery"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/imagegallery.rb
class Imagegallery < ApplicationRecord
    
    has_many_attached :images  #active storage
    belongs_to :user #association for unique 
    validate :acceptable_image
    validates :title, presence: true
    validates :caption, presence: true
    validates :tag_list, presence: true
    acts_as_taggable #tags
    paginates_per 4


    def acceptable_image
        if images.attached? == false
            errors.add(:images,"image must be attached")
        end
           images.each do|image|
        if !image.content_type.in?(%('image/jpeg image/png))
            errors.add(:images, 'needs to be a JPEG or PNG')
         end
            end
    end
end

app/controllers/imagegalleries_controller.rb
class ImagegalleriesController < ApplicationController
  before_action :set_imagegallery, only: [:show, :edit, :update, :destroy ]
 
  # GET /imagegalleries
  # GET /imagegalleries.json
 
  # def index
   
  #     @imagegalleries = current_user.imagegalleries.page( params[:page])
  
  # end

  def index
    @q = Imagegallery.ransack(params[:q])  
    if current_user && current_user.admin?     
      @imagegalleries = Imagegallery.all.page(params[:page])
      @imagegalleries = @q.result.page(params[:page])
    elsif current_user
      @imagegalleries = current_user.imagegalleries.page(params[:page])       
      @q  = current_user.imagegalleries.ransack(params[:q])       
      @imagegalleries = @q.result.page(params[:page])
    end    
  end

  # GET /imagegalleries/1
  # GET /imagegalleries/1.json
  def show
  end

  # GET /imagegalleries/new
  def new
    @imagegallery = Imagegallery.new
  end

  # GET /imagegalleries/1/edit
  def edit
  end

  # POST /imagegalleries
  # POST /imagegalleries.json
  def create
    @imagegallery = Imagegallery.new(imagegallery_params)
    @imagegallery.user = current_user
    respond_to do |format|
      if @imagegallery.save        
        ImagegalleryMailer.new_imagegallery(@imagegallery).deliver_now
        format.html { redirect_to @imagegallery, notice: 'Imagegallery was successfully created.' }
        format.json { render :show, status: :created, location: @imagegallery }
      else
        format.html { render :new }
        format.json { render json: @imagegallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imagegalleries/1
  # PATCH/PUT /imagegalleries/1.json
  def update
    respond_to do |format|
      if @imagegallery.update(imagegallery_params)
          if current_user && current_user.admin?
            ImagegalleryMailer.edit_imagegallery(@imagegallery).deliver_now
          end
        format.html { redirect_to @imagegallery, notice: 'Imagegallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @imagegallery }
      else
        format.html { render :edit }
        format.json { render json: @imagegallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imagegalleries/1
  # DELETE /imagegalleries/1.json
  def destroy    
    @imagegallery.destroy 
      
    if current_user && current_user.admin?
    ImagegalleryMailer.destroy_imagegallery(@imagegallery).deliver_now
    end

    respond_to do |format|
      format.html { redirect_to imagegalleries_url, notice: 'Imagegallery was successfully destroyed.' }
      format.json { head :no_content } 
    end
  end

  def delete_upload
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge 
    redirect_back(fallback_location: imagegalleries_url)
  end
 
  # All Images shown here
  # def showallimages    
  #   if user_signed_in?  
              
  #       @imagegalleries = current_user.imagegalleries.page( params[:page])
      
  #       redirect_to "/imagegalleries"
  
  #   else
  #       @imagegalleries = Imagegallery.all.page( params[:page])
    
  #       render template: "imagegalleries/showallimages"
  #   end
  # end
# def showallimages
#   if  current_user && current_user.admin?
#     @imagegalleries = Imagegallery.all.page( params[:page])
    
#         render template: "imagegalleries/showadminpage"
#   elsif user_signed_in?
#     @imagegalleries = current_user.imagegalleries.page( params[:page])
      
#         redirect_to "/imagegalleries"
#   else
#     @imagegalleries = Imagegallery.all.page( params[:page])
    
#     render template: "imagegalleries/showallimages"
#   end
# end

  def showallimages 
    if current_user && current_user.admin?
      @imagegalleries = Imagegallery.all.page(params[:page])
      @q = Imagegallery.ransack(params[:q])  
      @imagegalleries = @q.result.page(params[:page])
    elsif current_user
    # @imagegalleries = current_user.imagegalleries.page(params[:page])

    @imagegalleries = Imagegallery.all.page(params[:page])
      redirect_to "/imagegalleries"
      @q  = current_user.imagegalleries.ransack(params[:q])       
      @imagegalleries = @q.result.page(params[:page])
    else
      @imagegalleries = Imagegallery.all.page(params[:page])
      @q = Imagegallery.ransack(params[:q])  
      @imagegalleries = @q.result.page(params[:page])
    end    
  end

  def showgallery
    if current_user 
      @imagegalleries = Imagegallery.all.page(params[:page])
      @q = Imagegallery.ransack(params[:q])  
      @imagegalleries = @q.result.page(params[:page])

    else
      @imagegalleries = Imagegallery.all.page(params[:page])
      @q = Imagegallery.ransack(params[:q])  
      @imagegalleries = @q.result.page(params[:page])
    end
  end

  def tagged
    if params[:tag].present?
      if current_user && current_user.admin?
        @imagegalleries=Imagegallery.tagged_with(params[:tag]).page( params[:page])
        render template: "imagegalleries/showrelatedtags"
      elsif current_user
        @imagegalleries=current_user.imagegalleries.tagged_with(params[:tag]).page( params[:page])
        render template: "imagegalleries/showrelatedtags"        
      end
    else
      @imagegalleries = Imagegallery.all
    end
  end
 
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_imagegallery
    @imagegallery = Imagegallery.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def imagegallery_params
    params.require(:imagegallery).permit(:title, :caption, :tag_list, :public , images: [] )
  end

end

app/helpers/imagegalleries_helper.rb
module ImagegalleriesHelper
end

app/views/imagegalleries/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:category] %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/imagegalleries/edit.html.erb
<div class="conatiner">
    <div class="row justify-content-center">
    <div class="d-flex flex-column mt-2 border-secondary p-4 bg-info">
    <h1 class="d-flex justify-content-center mb-4 bg-light rounded-pill px-5 py-2 text-info mx-4">Editing ImageGallery</h1>
<div>
     <p>   <%= render 'form', imagegallery: @imagegallery %> </p>
      
     <p class="d-flex justify-content-around">   <%= link_to 'Show', @imagegallery ,:class=>"btn btn-dark"%> 
      
        <% if current_user && current_user.admin %> 
                        <%= link_to 'Back', root_path, :class => 'btn btn-dark' %>
                      <% else %>
                            <%= link_to 'Back', imagegalleries_path, :class => 'btn btn-dark' %> 
                      <% end %>
      
    </p>
     
</div>   
    </div>
    </div>
</div>

app/views/imagegalleries/index.html.erb
 
 <%# <p id="notice"><%= notice %>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1 ,shrink-t0-fit=no">
       <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"   integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"  crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
  
   <script>   $(document).ready(function(){
          $('.tag-search-form').submit(function(e){
            var new_action_url = $(this).attr('action') + "/" + $('#tag', this).val();
            $(this).attr('action', new_action_url)
          });
        });
  </script>

    <div class="container-fluid p-0">
              <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                  <a class="navbar-brand disabled" >IMAGE GALLERY</a>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                  <ul class=" navbar-nav mr-auto mt-2 mt-lg-0  ">
                    <li class="mr-3">
                      <a > <%= link_to 'HOME', showallimages_path, :class => 'btn btn-info' %> </a>
                    </li>                     
                    
                    <li class="nav-item pr-3">
                       <p class="text-white welcomeCurrentUser">WELCOME : <%= current_user.email.split('@')[0] %></p>
                    </li>            
                  </ul>    
                  <ul class="nav navbar-nav navbar-right ">  
                    <li class="mr-3" >
                       <a > <%= link_to 'UPLOAD', new_imagegallery_path, :class => 'btn btn-primary my-1' %></a>
                    </li> 
                     <li class="mr-3" >
                       <a > <%= link_to 'GALLERY',showgallery_path, :class => 'btn btn-primary my-1' %></a>
                    </li> 
                    <li class="mr-3">
                     <a> <%= link_to 'Sign Out' ,destroy_user_session_path, :class => 'btn btn-danger my-1', :method => :get %></a>
                    </li>                    
                  </ul> 
                </div>
              </nav>       
     </div>
  

 <div class="container-fluid">
    <div class="row">
          <div class=" col-sm-12 col-md-2">
          </div>
        <div class=" col-sm-12 col-md-8 ">
            <div class="d-flex flex-wrap flex-row  justify-content-center ">  
                  <% @imagegalleries.each do |imagegallery| %>
                  <% if imagegallery.public? || !current_user.admin? %> 
                  <div class="card mt-4 mx-2 "  >      
                            <div style="height:auto;" class="d-flex flex-wrap flex-row  justify-content-center ">
                             <% (0...imagegallery.images.count).each do |image| %>
                                 <div class="d-flex flex-column flex-wrap">
                                        <%= image_tag(imagegallery.images[image],style:'width:16rem', class:'img-fluid my-2 mx-2 rounded onHoverCardImg') %> 
                                        <%= link_to 'Delete Image', delete_upload_imagegallery_url(imagegallery.images[image]), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-info align-self-center" %>                             
                                 </div>
                                  <%end%>
                            </div>
                            <div class="text-center ">
                              
                                <p class="card-text card-text-edit mt-2 "><b>Title : </b><%=   imagegallery.title  %> </p>                       
                                <p class="card-text card-caption-edit "><b> Caption : </b><%=  imagegallery.caption  %>  </p>    
                                <p class="card-text card-tag-edit "> 
                                        <%# <p> Tags :<% imagegallery.tag_list.each do |tag|  <%= link_to tag, tag_path(tag: tag) %> 
                                        <b>Tags : </b> <%= imagegallery.tag_list %>                            
                                </p>                 
                                <p class="card-text mt-1 mb-1"><small><b>Created on  : </b><%= imagegallery.created_at.to_s.split(' ')[0] %>  </small>  </p>
                                <p class="card-text  mb-1"><small><b>Updated on  : </b><%= imagegallery.updated_at.to_s.split(' ')[0] %>   </small> </p>
                                
                                <p  class="card-text d-flex justify-content-around my-2">
                                  <%= link_to 'Show', imagegallery ,:class=>"btn btn-info"%>
                                  <%= link_to 'Edit', edit_imagegallery_path(imagegallery) ,:class=>"btn btn-info"%>
                                  <%= link_to 'Destroy', imagegallery, method: :delete, data: { confirm: 'Are you sure?' } ,:class=>"btn btn-info"%>
                                </p>
                          </div>     
                  </div>
                  <% end %>
                  <% end %>
              </div> 
         </div>
    
          <div class="col-sm-12 col-md-2 "> 
              <div class="border p-2 mt-4" >
                      <div>         <h3 class="text-secondary border-bottom"> Search </h3>
                      </div>
                      <div >                       
                                <%= search_form_for @q do |f| %>
                                   <h5 class="mt-3 mb-2"> <%= f.label :title_or_caption  %> </h5>
                                    <%= f.text_field  :title_or_caption_cont, class: 'form-control',placeholder: "Search title / caption", :required => 'required' %>
                                    <%= f.submit class: 'btn btn-primary mb-3 mt-2' %>
                                <% end %>
                      </div> 
                      
                        <div  > <h5 class="my-2">Tag</h5>
                                  <%= form_tag tagged_path(tag: tag), :class => 'form-inline', :method => :get do  %> 
                                     <%= text_field_tag :tag ,params[:tag] , class: 'form-control setwidthofTagInputElement', placeholder: "Search tag", :required => 'required'%> 
                                     <%= submit_tag 'Search' , :name =>nil , :class => 'btn btn-primary mb-3 mt-2'%>  
                                  <% end %>  
                        </div>  
                            
            </div>              
        </div>
    </div>
</div>


<div class="m-5 d-flex justify-content-center">
   <%= paginate @imagegalleries %>
</div>

 <%# # if user_signed_in?            
#   @imagegalleries = current_user.imagegalleries.page( params[:page])     
#   redirect_to "/imagegalleries"  
# else
#   @imagegalleries = Imagegallery.all.page( params[:page])  
#   render template: "imagegalleries/showallimages"
# end %>

app/views/imagegalleries/new.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1 ,shrink-t0-fit=no">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>





<div class="conatiner">
    <div class="row justify-content-center">
    <div class="d-flex flex-column mt-2 border border-secondary p-4 bg-info">
        <h1 class="d-flex justify-content-center mb-4 bg-light rounded-pill px-5 py-2 text-info mx-4">New ImageGallery</h1>
        <div>
          <p>  <%= render 'form', imagegallery: @imagegallery %>  </p>

           <p> <% if current_user && current_user.admin %> 
                        <%= link_to 'Back', showallimages_path, :class => 'btn btn-dark' %>
                <% else %>
                      <%= link_to 'Back', imagegalleries_path, :class => 'btn btn-dark' %> 
                <% end %>
          </p>
        <div>
    </div>
    </div>
</div>

app/views/imagegalleries/show.html.erb
<p id="notice"><%= notice %></p>
<div class="conatiner ">
    <div class="row justify-content-center ">
    <div class="d-flex flex-column mt-2 border border-secondary p-4 bg-light">

          <p>
            <strong>Title:</strong>
            <%= @imagegallery.title %>
          </p>
         

          <div style="height:auto" class="d-flex justify-content-center flex-wrap">
              <% (0...@imagegallery.images.count).each do |image| %>
              <%= image_tag(@imagegallery.images[image],style:'width:18rem', class:'img-fluid my-2 mx-2') %> 
             <%end%>
          </div>

          <p class="my-3">
            <strong>Caption:</strong>
            <%= @imagegallery.caption %>
          </p>
         

          <p class="d-flex justify-content-around">
          
              <%# <%= link_to 'Edit', edit_imagegallery_path(@imagegallery) , :class => 'btn btn-dark'%> 
         
              <% if current_user && current_user.admin %> 
                        <%= link_to 'Back', root_path, :class => 'btn btn-dark' %>
              <% else  %>                          
                        <%= link_to 'Back', imagegalleries_path, :class => 'btn btn-dark' %>                         
             <% end %>

          </p>
</div>
</div>
</div>

app/views/imagegalleries/showallimages.html.erb
 
 <%# <p id="notice"><%= notice %>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1 ,shrink-t0-fit=no">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <div class="container-fluid p-0">
              <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>            
             
             <% if current_user && current_user.admin?  && current_user.admin?  %> 
           
             <% else %>
                <a class="navbar-brand disabled" >IMAGE GALLERY</a>
            <% end %>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                  <ul class=" navbar-nav mr-auto mt-2 mt-lg-0  ">
                    <li class="nav-link active">
                        <a > WELCOME </a>  <% if current_user %> :<a class="ml-2"> <%= current_user.email.split('@')[0] %>  </a> <% else %>   <% end %>
                   </li>
                                   
                  </ul>    
              
                  <ul class="nav navbar-nav navbar-right">    
                  
          <% if current_user && current_user.admin?  %>                      
                    <li class="mr-3">
                       <a > <%= link_to 'UPLOAD', new_imagegallery_path, :class => 'btn btn-primary my-1' %></a>
                    </li>   
                     <li class="mr-3">                                      
                         <a > <%= link_to "Sign Out", destroy_user_session_path, :class => 'btn btn-danger my-1', :method => :get %> </a>
                    </li>     
           <% else %> 
                    <li>                                      
                         <a class="mr-2"> <%= link_to "Log in", new_user_session_path, :class => 'btn btn-warning my-1'%>  </a>
                    </li>
                    <li>
                         <a class="mr-2">  <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-warning my-1'%>  </a>
                    <li>
            <% end %>
                  </ul> 
                </div>
              </nav>       
     </div>
  
  <% if current_user && current_user.admin?  %>     
  <% else %>
      <div class="container">
          <h2 class=" my-5 d-flex  text-justify text-center bg-gradient-warning text-dark">
          GalleryApp is a favorite among gallery management applications and this is a great example of simple, persuasive gallery.</h2>
      </div>
   <% end %>

      





<% if current_user && current_user.admin?  %>     

  <div class="container-fluid">
      <div class="row">
          <div class=" col-sm-12 col-md-2">
          </div>
          <div class=" col-sm-12 col-md-8 ">
            <div class="d-flex flex-wrap flex-row  justify-content-center ">  
                  <% @imagegalleries.each do |imagegallery| %>
                  <div class="card mt-4 mx-2 "  >      
                            <div style="height:auto;" class="d-flex flex-wrap flex-row  justify-content-center ">
                             <% (0...imagegallery.images.count).each do |image| %>
                                 <div class="d-flex flex-column flex-wrap">
                                        <%= image_tag(imagegallery.images[image],style:'width:16rem', class:'img-fluid my-2 mx-2 rounded onHoverCardImg') %> 
                                        <%= link_to 'Delete Image', delete_upload_imagegallery_url(imagegallery.images[image]), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-info align-self-center" %>                             
                                 </div>
                                  <%end%>
                            </div>
                            <div class="text-center ">
                                <p class="card-text card-text-edit mt-2 "><b>Title : </b><%=   imagegallery.title  %> </p>                       
                                <p class="card-text card-caption-edit "><b> Caption : </b><%=  imagegallery.caption  %>  </p> 
                                <p class="card-text card-published-edit"><small><b>Published By : </b><%=   imagegallery.user.email.split('@')[0] %> </small></p>                           
                                                       
                                <p class="card-text card-tag-edit "> 
                                        <%# <p> Tags :<% imagegallery.tag_list.each do |tag|  <%= link_to tag, tag_path(tag: tag) %> 
                                        <b>Tags : </b> <%= imagegallery.tag_list %>                            
                                </p>                 
                                <p class="card-text mt-1 mb-1"><small><b>Created on  : </b><%= imagegallery.created_at.to_s.split(' ')[0] %>  </small>  </p>
                                <p class="card-text  mb-1"><small><b>Updated on  : </b><%= imagegallery.updated_at.to_s.split(' ')[0] %>   </small> </p>

                                <p  class="card-text d-flex justify-content-around my-2">
                                  <%= link_to 'Show', imagegallery ,:class=>"btn btn-info"%>
                                  <%= link_to 'Edit', edit_imagegallery_path(imagegallery) ,:class=>"btn btn-info"%>
                                  <%= link_to 'Destroy', imagegallery, method: :delete, data: { confirm: 'Are you sure?' } ,:class=>"btn btn-info"%>
                                </p>
                          </div>     
                  </div>
                  <% end %>
              </div> 
          </div>
    
            <div class="col-sm-12 col-md-2  "> 
                  <div class="border p-2 mt-4">
                      <div>         <h3 class="text-secondary border-bottom"> Search </h3>
                      </div>
                     <div >
                       
                                <%= search_form_for @q do |f| %>
                                   <h5 class="mt-3 mb-2"> <%= f.label :title_or_caption  %> </h5>
                                    <%= f.text_field  :title_or_caption_cont, class: 'form-control',placeholder: "Search title / caption", :required => 'required' %>
                                    <%= f.submit class: 'btn btn-primary mb-3 mt-2' %>
                                <% end %>
                      </div> 
                      
                        <div  > <h5 class="my-2">Tag</h5>
                                <%= form_tag tagged_path(tag: tag), :class => 'form-inline', :method => :get do  %> 
                                    <%= text_field_tag :tag ,params[:tag] , class: 'form-control setwidthofTagInputElement', placeholder: "Search tag", :required => 'required'%> 
                                    <%= submit_tag 'Search' , :name =>nil , :class => 'btn btn-primary mb-3 mt-2'%>  
                                <% end %>  
                        </div>   
                            
                     </div>      
                            
             </div>
      </div>
</div>

 
 
 
 
  <% else %>



        <div class="container  ">
                 <div class="d-flex flex-wrap flex-row justify-content-center ">  
          
                  <% @imagegalleries.each do |imagegallery| %>
                        <% if imagegallery.public? %>
                        <div class="card mt-4 mx-2" >      
                               <div style="height:auto;" class="d-flex flex-wrap flex-row  justify-content-center ">
                                  <% (0...imagegallery.images.count).each do |image| %>
                                  <%= image_tag(imagegallery.images[image],style:'width:16rem', class:'img-fluid my-2 mx-2 rounded onHoverCardImg') %> 
                                <%end%>
                              </div>    
                               <div class="text-center ">
                                  <p class="card-text card-text-edit mt-2 "><b>Title : </b><%=   imagegallery.title  %> </p>                       
                                  <p class="card-text card-caption-edit "><b> Caption : </b><%=  imagegallery.caption  %>  </p> 
                                  <p class="card-text card-published-edit"><small><b>Published By : </b><%=   imagegallery.user.email.split('@')[0] %> </small></p>                           
                                                                  
                               </div>                                                        
                        </div>
                        <% end %>
                  <% end %>
               </div>  
        
        </div>

<% end %>


<div class="m-5 d-flex justify-content-center">
   <%= paginate @imagegalleries %>
</div>






  <% if current_user && current_user.admin?  %>     
  <% else %>
      <footer class="footer1 bg-dark sticky-bottom">
      
          <ul class="social-menu2 mt-4">
            <li ><a href="https://www.facebook.com/colorlib"><i class="fa fa-facebook"  aria-hidden="true" ></i></a></li>
            <li ><a href="https://twitter.com/colorlib"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
            <li ><a href="https://www.youtube.com/channel/UCOaovjLNXdIch2vLFsw_uew"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
            <li ><a href="https://plus.google.com/100289203607749737039"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
            <li ><a href="https://instagram.com"><i class="fa fa-google" aria-hidden="true"></i></a></li>
            <li ><a href="https://github.com/puikinsh/"><i class="fa fa-github" aria-hidden="true"></i></a></li>
          </ul>
             
          <p class="text-white">Design By Sahil</p>
  </footer>
<% end %>